backend:
  name: git-gateway
  branch: master

media_folder: "/src/pages/blog/img"
public_folder: "img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "about"
    label: "За Нас"
    folder: "src/pages/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "за нас"}
      - {label: "Path", name: "path", widget: "hidden", default: "/za_nas"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "djs"
    label: "DJs"
    folder: "src/pages/djs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "DJ"}
      - {label: "Path", name: "path", widget: "hidden", default: "/djs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Bio", name: "Bio", widget: "markdown"}
      - {label: "Facebook", name: "fb", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}
      - {label: "Soundcloud", name: "soundcloud", widget: "string"}
      - {label: "Promo Mix", name: "promoMix", widget: "string"}
      - {label: "Image", name: "img", widget: "string"}
      - {label: "Instagram", name: "instagram", widget: "string"}
      - {label: "Mixcloud", name: "mixcloud", widget: "string"}
